export enum ACTION_TYPES {
    SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES',
    SET_TRENDING_SHOWS = 'SET_TRENDING_SHOWS',
    SET_MOST_LIKED = 'SET_MOST_LIKED',
    SET_SERIES = 'SET_SERIES',
    SET_MUSIC = 'SET_MUSIC',
    SET_HERO_DATA = 'SET_HERO_DATA',
    SET_LOADING = 'SET_LOADING',
    SET_ERROR = 'SET_ERROR'
}
